name: Periodic Update

on:
  schedule:
    - cron: '0 */4 * * *' # هر چهار ساعت یکبار

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Repository
        run: |
          git config --local user.email "mohsenmojadam2019@gmail.com.com"
          git config --local user.name "mohsenmojadam2019"
          git pull origin main

